#!/usr/bin/env sh

spacebar -m config text_font         "Helvetica Neue:Bold:12.0"
spacebar -m config icon_font         "Font Awesome 5 Brands:Regular:14"
spacebar -m config background_color  0xff202020
spacebar -m config foreground_color  0xffa8a8a8
spacebar -m config space_icon_strip     4 5 6 7 8 9  駱     稜 
spacebar -m config power_icon_strip  
spacebar -m config space_icon        
spacebar -m config clock_icon        
spacebar -m config clock_format      "%d/%m/%y %R"

echo "spacebar configuration loaded.."
